// Generated by CoffeeScript 1.6.3
var Account, List;

List = require('./list');

Account = (function() {
  function Account() {}

  Account.prototype.details = function(callback) {
    if (typeof callback === "function") {
      callback(null);
    }
    return this;
  };

  Account.prototype.operations = function(selector) {
    return new OperationList().filter(selector);
  };

  return Account;

})();

module.exports = Account;
