// Generated by CoffeeScript 1.6.3
var List, Operation, Payment, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

List = require('./list');

Operation = (function() {
  function Operation() {}

  Operation.prototype.details = function(callback) {
    if (typeof callback === "function") {
      callback(null);
    }
    return this;
  };

  return Operation;

})();

Payment = (function(_super) {
  __extends(Payment, _super);

  function Payment() {
    _ref = Payment.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Payment.prototype.request = function(callback) {
    if (typeof callback === "function") {
      callback(null);
    }
    return this;
  };

  Payment.prototype.process = function(callback) {
    if (typeof callback === "function") {
      callback(null);
    }
    return this;
  };

  return Payment;

})(Operation);

module.exports = Operation;
