// Generated by CoffeeScript 1.6.3
var Core, Provider;

Core = require('./core');

Provider = (function() {
  function Provider() {}

  Provider.prototype.account = function(id) {
    return new Account(id);
  };

  Provider.prototype.createPayment = function() {};

  return Provider;

})();

module.exports = Provider;
