// Generated by CoffeeScript 1.6.1
var Account;

Account = (function() {

  function Account(service) {
    this.service = service;
  }

  Account.prototype.operations = function() {};

  Account.prototype.info = function(callback) {
    this.service.invoke({
      method: 'post',
      name: 'account-info',
      callback: callback
    });
    return this;
  };

  return Account;

})();

module.exports = Account;
