// Generated by CoffeeScript 1.6.3
var Operation;

Operation = (function() {
  function Operation(service, data) {
    this.service = service;
    this.data = data != null ? data : {};
  }

  Operation.prototype.request = function(callback) {
    this.service.invoke({
      method: 'post',
      name: 'request-payment',
      data: this.data,
      callback: callback
    });
    return this;
  };

  Operation.prototype.process = function(callback) {
    var data;
    data = {
      request_id: this.data.request_id
    };
    this.service.invoke({
      method: 'post',
      name: 'process-payment',
      data: data,
      callback: callback
    });
    return this;
  };

  return Operation;

})();

module.exports = Operation;
