// Generated by CoffeeScript 1.6.1
var Payment;

Payment = (function() {

  function Payment(service) {
    this.service = service;
    this.data = {};
  }

  Payment.prototype.request = function(callback) {
    this.service.invoke({
      method: 'post',
      name: 'request-payment',
      data: null,
      onComplete: callback
    });
    return this;
  };

  Payment.prototype.process = function(callback) {
    this.service.invoke({
      method: 'post',
      name: 'process-payment',
      data: null,
      onComplete: callback
    });
    return this;
  };

  return Payment;

})();

module.exports = Payment;
