// Generated by CoffeeScript 1.6.3
var DEFAULT_CHARSET, DEFAULT_HOST, DEFAULT_PORT, Service, https, iconv, qs;

https = require('https');

qs = require('querystring');

iconv = require('iconv-lite');

DEFAULT_HOST = 'money.yandex.ru';

DEFAULT_PORT = 443;

DEFAULT_CHARSET = 'utf-8';

Service = (function() {
  function Service(token) {
    this.token = token;
  }

  Service.prototype.path = function(options) {
    return '/api/' + options.name;
  };

  Service.prototype.headers = function(body) {
    return {
      'authorization': 'Bearer ' + this.token,
      'content-type': 'application/x-www-form-urlencoded; charset=' + this.charset,
      'content-length': body.length
    };
  };

  Service.prototype.serialize = function(data) {
    return qs.stringify(data);
  };

  Service.prototype.encode = function(text) {
    return iconv.encode(text, 'utf-8');
  };

  Service.prototype.parse = function(data, contentType) {
    switch (contentType) {
      case 'application/json':
        return JSON.parse(iconv.decode(data));
    }
  };

  Service.prototype.invoke = function(options) {
    var body, request;
    body = this.body(options);
    request = https.request({
      host: this.host,
      port: this.port,
      method: options.method,
      path: this.path(options),
      headers: this.headers(body)
    });
    request.on('response', function(response) {
      var chunks;
      chunks = [];
      response.on('readable', function() {
        chunks.push(response.read());
        return void 0;
      });
      response.on('end', function() {
        var data;
        data = Buffer.concat(chunks);
        if (typeof options.callback === "function") {
          options.callback(null, data);
        }
        return void 0;
      });
      return void 0;
    });
    request.on('error', function(error) {
      if (typeof options.callback === "function") {
        options.callback(error);
      }
      return void 0;
    });
    request.end(body);
    return this;
  };

  return Service;

})();

module.exports = Service;
